# Generated by Django 5.2.7 on 2025-11-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите название курса", max_length=200, verbose_name="Название курса"
                    ),
                ),
                ("description", models.TextField(help_text="Подробное описание курса", verbose_name="Описание курса")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение для превью курса",
                        null=True,
                        upload_to="courses/previews/",
                        verbose_name="Превью курса",
                    ),
                ),
                (
                    "last_notification_sent",
                    models.DateTimeField(
                        blank=True,
                        help_text="Время последнего отправленного уведомления подписчикам о курсе",
                        null=True,
                        verbose_name="Последнее уведомление отправлено",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите название урока", max_length=200, verbose_name="Название урока"
                    ),
                ),
                ("description", models.TextField(help_text="Подробное описание урока", verbose_name="Описание урока")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение для превью урока",
                        null=True,
                        upload_to="lessons/previews/",
                        verbose_name="Превью урока",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        help_text="Укажите ссылку на видео урока (YouTube, Vimeo и т.д.)",
                        max_length=500,
                        verbose_name="Ссылка на видео",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["course", "id"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
                "ordering": ["-created_at"],
            },
        ),
    ]
