# Generated by Django 5.2.7 on 2025-11-17 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="owner",
            field=models.ForeignKey(
                help_text="Пользователь, создавший курс",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец курса",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                help_text="Выберите курс, к которому относится урок",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="lms.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="owner",
            field=models.ForeignKey(
                help_text="Пользователь, создавший урок",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец урока",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                help_text="Курс, на который подписан пользователь",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribers",
                to="lms.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь, подписанный на курс",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["user", "course"], name="lms_subscri_user_id_1ddf05_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("user", "course")},
        ),
    ]
