#!/bin/sh
set -e

echo "=========================================="
echo "Production .env Generator"
echo "=========================================="
echo ""

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
    echo "✓ .env file already exists. Skipping generation to preserve existing secrets."
    echo "  If you need to regenerate, delete .env manually and run this script again."
    exit 0
fi

echo "→ Validating required environment variables..."

if [ -z "$SERVER_IP" ]; then
    echo "✗ ERROR: SERVER_IP environment variable is not set!"
    echo "  This should be passed from GitHub Actions secrets."
    exit 1
fi

if [ -z "$STRIPE_SECRET_KEY" ]; then
    echo "✗ ERROR: STRIPE_SECRET_KEY environment variable is not set!"
    echo "  This should be passed from GitHub Actions secrets."
    exit 1
fi

if [ -z "$STRIPE_PUBLISHABLE_KEY" ]; then
    echo "✗ ERROR: STRIPE_PUBLISHABLE_KEY environment variable is not set!"
    echo "  This should be passed from GitHub Actions secrets."
    exit 1
fi

echo "✓ All required environment variables are set"
echo ""

echo "→ Generating secrets..."

# Generate secure secrets
GENERATED_SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(50))")
GENERATED_POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '\n')

echo "✓ SECRET_KEY generated (50 chars, URL-safe, no $ symbol)"
echo "✓ POSTGRES_PASSWORD generated (base64, 24 bytes)"
echo ""

# Export all variables for heredoc expansion
export SECRET_KEY="$GENERATED_SECRET_KEY"
export POSTGRES_PASSWORD="$GENERATED_POSTGRES_PASSWORD"
# GitHub Secrets already in environment: SERVER_IP, STRIPE_SECRET_KEY, STRIPE_PUBLISHABLE_KEY

echo "→ Creating .env file..."

# Using unquoted heredoc - variables will be expanded
cat > "$ENV_FILE" << EOF
# =============================================================================
# Production Environment Variables
# =============================================================================
# ⚠️  AUTO-GENERATED by scripts/generate-production-env.sh
# 📅 Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# 🚫 DO NOT COMMIT THIS FILE TO GIT!
# =============================================================================

# =============================================================================
# Django Settings
# =============================================================================

DEBUG=False

# Auto-generated Django secret key (URL-safe, no $ symbol)
SECRET_KEY=${SECRET_KEY}

# Server IP from GitHub Secrets
ALLOWED_HOSTS=${SERVER_IP},localhost,127.0.0.1
SITE_DOMAIN=${SERVER_IP}:8000
CORS_ALLOWED_ORIGINS=http://${SERVER_IP}:8000

# =============================================================================
# PostgreSQL Database
# =============================================================================

POSTGRES_DB=lms_db
POSTGRES_USER=lms_user

# Auto-generated secure password
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Docker service names (DO NOT CHANGE!)
POSTGRES_HOST=db
POSTGRES_PORT=5432

# =============================================================================
# Redis & Celery (Docker service names, DO NOT CHANGE!)
# =============================================================================

REDIS_URL=redis://redis:6379/0
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/0

# =============================================================================
# Stripe Payment Integration
# =============================================================================

# From GitHub Secrets
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}

# =============================================================================
# Email Settings
# =============================================================================

# Console backend (emails in logs) - change if you need real email sending
EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend

# Email notification cooldown (hours)
EMAIL_NOTIFICATION_COOLDOWN_HOURS=4

# Uncomment below if you need real SMTP email sending:
# EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# EMAIL_HOST=smtp.gmail.com
# EMAIL_PORT=587
# EMAIL_USE_TLS=True
# EMAIL_HOST_USER=${EMAIL_HOST_USER:-}
# EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-}
# DEFAULT_FROM_EMAIL=noreply@yourdomain.com

# =============================================================================
# Celery Tasks Configuration
# =============================================================================

# Days of inactivity before user blocking
INACTIVE_USER_DAYS=30

# =============================================================================
# Static & Media Files (Docker container paths, DO NOT CHANGE!)
# =============================================================================

STATIC_ROOT=/app/staticfiles
MEDIA_ROOT=/app/media
STATIC_URL=/static/
MEDIA_URL=/media/

# =============================================================================
# Logging
# =============================================================================

LOG_LEVEL=INFO

# =============================================================================
# Security Settings - HTTPS (Disabled for HTTP deployment)
# =============================================================================
# ⚠️  DO NOT uncomment these without SSL certificate!
# These settings are for HTTPS deployments with domain + SSL only.
# For IP-based deployment without SSL, keep them commented.
#
# SECURE_SSL_REDIRECT=True
# SECURE_HSTS_SECONDS=31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS=True
# SECURE_HSTS_PRELOAD=True
EOF

echo "✓ .env file created successfully!"
echo ""
echo "=========================================="
echo "Summary:"
echo "=========================================="
echo "✓ SECRET_KEY: Auto-generated (${#GENERATED_SECRET_KEY} chars)"
echo "✓ POSTGRES_PASSWORD: Auto-generated (24 bytes base64)"
echo "✓ STRIPE_SECRET_KEY: From GitHub Secrets"
echo "✓ STRIPE_PUBLISHABLE_KEY: From GitHub Secrets"
echo "✓ SERVER_IP: ${SERVER_IP}"
echo "✓ Total variables: ~25"
echo ""
echo "🎉 Production environment ready for deployment!"
echo "=========================================="
